language: php

php:
  - 7.3

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

addons:
  apt:
    packages:
      - wkhtmltopdf

install:
    - sudo apt-get update
    - wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
    - sudo dpkg -i "wkhtmltox_0.12.6-1.bionic_amd64.deb"
    - sudo mv wkhtmltopdf-amd64 /usr/local/bin/wkhtmltopdf
    - sudo chmod +x /usr/local/bin/wkhtmltopdf

cache:
  directories:
    - vendor